# Generated by Django 4.2.17 on 2025-12-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_usersettings_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reserve_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
