# Generated by Django 4.2.17 on 2025-12-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_reserve_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reserve_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve_children', to='finance.transaction'),
        ),
    ]
